project:
  type: "website"


website:
  title: "BSSw Fellowship Application (2024)"
  repo-url: "https://github.com/mfisher87/BSSw-fellowship-application-2024"
  repo-actions:
    - "edit"
    - "source"
    - "issue"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy;"

  sidebar:
    background: "#eee"
    style: "docked"
    search: true
    contents:
      - text: "Application materials"
        href: "application/index.md"
      - text: "Ideas"
        href: "ideas.md"
      - text: "Resources"
        href: "resources.md"


format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
